name: syndrumnet
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.10
  - numpy=1.24
  - scipy=1.10
  - pandas=2.0
  - networkx=3.1
  - scikit-learn=1.3
  - matplotlib=3.7
  - pyyaml=6.0
  - requests=2.31
  - tqdm=4.65
  - joblib=1.3
  - biopython=1.81
  - pip
  - pip:
    - mygene==3.2.2
    - pytest>=7.4.0
    - pytest-cov>=4.1.0
    - black>=23.7.0
    - mypy>=1.5.0
    - flake8>=6.1.0